### ISSUE TITLE
Ubuntu 14.04 support

### ISSUE THREAD

**Issue by falkerson** [CGenie/vagrant-fuel-dev#1]
Maybe it makes sense move to Ubuntu 14.04 to be fully synchronized with fuel

**Comment by CGenie** [comment]
Migration to 14.04 is a planned feature for this release of Mirantis OpenStack. I don't know if current package will work just like that with 14.04, I'll try to make some tests in spare time.

**Comment by CGenie** [comment]
Solved in https://github.com/CGenie/vagrant-fuel-dev/commit/43ef0bfa1a47abadf0fecb6f7c64d63e77e0c6c8
